import XCTest
@testable import AgentBabysitterCore

final class SessionTitleTests: XCTestCase {

    func testRealPromptsPassThrough() {
        XCTAssertEqual(SessionTitle.candidate(fromPromptText: "can u make websites for me?",
                                              isMeta: false),
                       "can u make websites for me?")
        XCTAssertEqual(SessionTitle.candidate(fromPromptText: "  fix the icon bug  \nmore detail",
                                              isMeta: false),
                       "fix the icon bug")
    }

    /// Every noise shape observed in real Claude Code / Codex transcripts.
    func testProtocolNoiseIsRejected() {
        let noise = [
            "<command-name>/goal</command-name> <command-message>goal</command-message>",
            "<local-command-stdout>Goal set: research</local-command-stdout>",
            "<system-reminder>recalled memory</system-reminder>",
            "<environment_context>\n<cwd>/tmp</cwd>",
            "<user_instructions>Follow AGENTS.md</user_instructions>",
            "<turn_context>model: gpt-5</turn_context>",
            "Caveat: the messages below were generated by the user",
            "[Request interrupted by user]",
            "[task started]",
            "",
            "   \n  ",
        ]
        for text in noise {
            XCTAssertNil(SessionTitle.candidate(fromPromptText: text, isMeta: false),
                         "should reject: \(text.prefix(40))")
        }
    }

    func testMetaLinesRejectedEvenWithPlainText() {
        XCTAssertNil(SessionTitle.candidate(
            fromPromptText: "A session-scoped Stop hook is now active", isMeta: true))
    }

    func testLongPromptsCappedAtOneLine() {
        let long = String(repeating: "word ", count: 50)
        let title = SessionTitle.candidate(fromPromptText: long, isMeta: false)
        XCTAssertEqual(title?.count, 80)
        XCTAssertTrue(title?.hasSuffix("…") == true)
    }

    func testReducerKeepsLastRealPromptThroughNoise() {
        var reducer = TranscriptReducer()
        func user(_ text: String, isMeta: Bool = false) -> TranscriptEntry {
            TranscriptEntry(kind: .user(UserPayload(text: text, toolResults: [])),
                            uuid: nil, timestamp: nil, sessionID: nil, cwd: nil,
                            isSidechain: false, isMeta: isMeta)
        }
        reducer.consume(user("fix the login bug"))
        XCTAssertEqual(reducer.lastUserPrompt, "fix the login bug")
        // Noise doesn't overwrite the real prompt…
        reducer.consume(user("<command-name>/clear</command-name>"))
        reducer.consume(user("hook notice", isMeta: true))
        XCTAssertEqual(reducer.lastUserPrompt, "fix the login bug")
        // …the next real prompt does.
        reducer.consume(user("now add tests"))
        XCTAssertEqual(reducer.lastUserPrompt, "now add tests")
        // Interrupts don't clear the title (the task is still the task).
        reducer.consume(user("[Request interrupted by user]"))
        XCTAssertEqual(reducer.lastUserPrompt, "now add tests")
    }
}
